// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv_Hu0CJnC7AkQhopk0hToKxEjVKy69Zc',
    appId: '1:478595585360:android:cb2af98064472891d3c855',
    messagingSenderId: '478595585360',
    projectId: 'restaurant-reservation-s-8657b',
    storageBucket: 'restaurant-reservation-s-8657b.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfncKAUE2C5nEe-KhCQdjzpqjb62y2HHM',
    appId: '1:478595585360:web:c5b57f2a75d4f50dd3c855',
    messagingSenderId: '478595585360',
    projectId: 'restaurant-reservation-s-8657b',
    authDomain: 'restaurant-reservation-s-8657b.firebaseapp.com',
    storageBucket: 'restaurant-reservation-s-8657b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJlVmy6b_rWkYe_gBoVltiRlC9CakgRuY',
    appId: '1:478595585360:ios:b7c03b57129cdc2ed3c855',
    messagingSenderId: '478595585360',
    projectId: 'restaurant-reservation-s-8657b',
    storageBucket: 'restaurant-reservation-s-8657b.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJlVmy6b_rWkYe_gBoVltiRlC9CakgRuY',
    appId: '1:478595585360:ios:b7c03b57129cdc2ed3c855',
    messagingSenderId: '478595585360',
    projectId: 'restaurant-reservation-s-8657b',
    storageBucket: 'restaurant-reservation-s-8657b.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfncKAUE2C5nEe-KhCQdjzpqjb62y2HHM',
    appId: '1:478595585360:web:2105547a083b9b1dd3c855',
    messagingSenderId: '478595585360',
    projectId: 'restaurant-reservation-s-8657b',
    authDomain: 'restaurant-reservation-s-8657b.firebaseapp.com',
    storageBucket: 'restaurant-reservation-s-8657b.firebasestorage.app',
  );

}