// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuK0_WwpUAYz64Als28Ph8dKzGkSV0eKI',
    appId: '1:498930849752:android:3d8c1962959fbd29e944ad',
    messagingSenderId: '498930849752',
    projectId: 'restaurant-reservation-s-97263',
    storageBucket: 'restaurant-reservation-s-97263.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtPBEC5W3SbTAyL4krrGWPjKt8hCeF6CI',
    appId: '1:498930849752:web:3be8bdd1f2374822e944ad',
    messagingSenderId: '498930849752',
    projectId: 'restaurant-reservation-s-97263',
    authDomain: 'restaurant-reservation-s-97263.firebaseapp.com',
    storageBucket: 'restaurant-reservation-s-97263.firebasestorage.app',
    measurementId: 'G-P2T0BSLKD9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn1-DzLoheZ4hKPjixoF7lzqqyHDIE108',
    appId: '1:498930849752:ios:dddc8de0f47c04d2e944ad',
    messagingSenderId: '498930849752',
    projectId: 'restaurant-reservation-s-97263',
    storageBucket: 'restaurant-reservation-s-97263.firebasestorage.app',
    iosBundleId: 'com.example.vendorApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn1-DzLoheZ4hKPjixoF7lzqqyHDIE108',
    appId: '1:498930849752:ios:dddc8de0f47c04d2e944ad',
    messagingSenderId: '498930849752',
    projectId: 'restaurant-reservation-s-97263',
    storageBucket: 'restaurant-reservation-s-97263.firebasestorage.app',
    iosBundleId: 'com.example.vendorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtPBEC5W3SbTAyL4krrGWPjKt8hCeF6CI',
    appId: '1:498930849752:web:6cebad857909c9b6e944ad',
    messagingSenderId: '498930849752',
    projectId: 'restaurant-reservation-s-97263',
    authDomain: 'restaurant-reservation-s-97263.firebaseapp.com',
    storageBucket: 'restaurant-reservation-s-97263.firebasestorage.app',
    measurementId: 'G-XQ9MZ8CX9Z',
  );

}